#!/usr/bin/env bash
# This script connects to the server using SSH with a specified private key

# Define the server IP and user
SERVER_IP="34.207.148.4"
USER="ubuntu"

# Connect using the private key
ssh -i ~/.ssh/school "$USER@$SERVER_IP"
