#!/usr/bin/env bash
# This script creates an RSA key pair with a 4096-bit key size and a passphrase.

# Define the key file name and passphrase
KEY_FILE="school"
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -f "$KEY_FILE" -N "$PASSPHRASE"
